spring:
  datasource:
    url: jdbc:mysql://localhost:3306/application?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD:}
    # 数据库初始化配置
    sql:
      init:
        mode: always 