server:
  port: 8083

spring:
  application:
    name: app3

management:
  server:
    port: 8083
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 配置common模块的HelloWorld服务
common:
  service:
    hello-world-enabled: true
    welcome-message: "来自App3的问候消息!" 