server:
  port: 8083

spring:
  application:
    name: app3

management:
  server:
    port: 8083
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 